version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/app/src/node_modules
      - .:/usr/app/src
    stdin_open: true
    restart: unless-stopped
